Reset to https://launchpad.net/ubuntu/+source/initramfs-tools/0.142ubuntu25.5

diff --git a/debian/tests/test-common b/debian/tests/test-common
--- a/debian/tests/test-common
+++ b/debian/tests/test-common
@@ -26,12 +26,8 @@ ppc64el)
 	# Slowest execution seen in Ubuntu ppc64el autopkgtest: 230 seconds
 	QEMU_TIMEOUT=600
 	;;
-s390x)
-	# Slowest execution seen in Ubuntu s390x autopkgtest: 58 seconds
-	QEMU_TIMEOUT=120
-	;;
 *)
-	QEMU_TIMEOUT=60
+	QEMU_TIMEOUT=120
 esac
 
 if [ -n "${AUTOPKGTEST_TMP-}" ]; then
@@ -81,7 +77,7 @@ EOF
 chmod a+x "${ROOTDIR}/sbin/init"
 cp /usr/lib/klibc/bin/sh "${ROOTDIR}/bin/sh"
 cp /usr/lib/klibc/bin/poweroff "${ROOTDIR}/bin/poweroff"
-cp "$(dpkg -L libklibc | grep '^/lib/klibc.*\.so$')" "${ROOTDIR}/lib/"
+cp "$(dpkg -L libklibc | grep '^\(/usr\)\?/lib/klibc.*\.so$')" "${ROOTDIR}/lib/"
 
 # VM output file
 OUTPUT="${BASEDIR}/output.log"
@@ -143,6 +139,7 @@ build_initramfs() {
 build_fs_ext2() {
 	local dir="${1}"
 	local disk="${2}"
+	local label="${3-}"
 
 	# Get directory size
 	local blocks="$(du --summarize "${dir}" | cut -f 1)"
@@ -154,7 +151,7 @@ build_fs_ext2() {
 
 	# genext2fs writes status messages to stderr; hide that from
 	# autopkgtest
-	genext2fs 2>&1 -b "${blocks}" -N "${inodes}" -U -d "${dir}" "${disk}"
+	genext2fs 2>&1 -b "${blocks}" -N "${inodes}" ${label:+-L "$label"} -U -d "${dir}" "${disk}"
 }
 
 build_rootfs_ext2() {
@@ -162,30 +159,71 @@ build_rootfs_ext2() {
 }
 
 _run_qemu() {
-	local extra_append="$1"
+	local append="$1"
 	shift
 
 	echo "I: Running qemu (with a timeout of $QEMU_TIMEOUT seconds)..."
 	timeout --foreground "$QEMU_TIMEOUT" \
-		debian/tests/run-qemu /boot/vmlinu*-"${KVER}" "${INITRAMFS}" \
-		"root=/dev/${ROOTDISK_LINUX_NAME} ${extra_append}" -nographic \
-		-drive "file=${ROOTDISK},if=${ROOTDISK_QEMU_IF},media=disk,format=raw" \
+		debian/tests/run-qemu /boot/vmlinu*-"${KVER}" "${INITRAMFS}" "${append}" \
+		-nographic -chardev stdio,id=char0 -serial chardev:char0 "$@" \
 		${USRDISK:+-drive "file=${USRDISK},if=${USRDISK_QEMU_IF},media=disk,format=raw"} \
-		-chardev stdio,id=char0 -serial chardev:char0 "$@" | tee "${OUTPUT}"
+		| tee "${OUTPUT}"
+}
+
+run_qemu_in_background() {
+	local rootdisk="$1"
+	local pidfile="$2"
+	local logfile="$3"
+	shift 3
+
+	echo "I: Running qemu in background..."
+	debian/tests/run-qemu /boot/vmlinu*-"${KVER}" "${INITRAMFS}" \
+		"root=/dev/${ROOTDISK_LINUX_NAME} panic=-1" -display none \
+		-drive "file=${rootdisk},if=${ROOTDISK_QEMU_IF},media=disk,format=raw" \
+		-device "virtio-net-pci,netdev=lan9,mac=52:54:00:12:33:21" \
+		-netdev "socket,id=lan9,listen=localhost:1234" \
+		-pidfile "${pidfile}" -serial "file:${logfile}" -daemonize "$@"
 }
 
 run_qemu_nocheck() {
 	# hide error messages from autopkgtest
-	_run_qemu "${1-}" 2>&1
+	_run_qemu "root=/dev/${ROOTDISK_LINUX_NAME} ${1-}" \
+		-drive "file=${ROOTDISK},if=${ROOTDISK_QEMU_IF},media=disk,format=raw" 2>&1
 }
 
 run_qemu() {
-	_run_qemu "panic=-1 $*" \
+	_run_qemu "root=/dev/${ROOTDISK_LINUX_NAME} panic=-1 $*" \
+		-drive "file=${ROOTDISK},if=${ROOTDISK_QEMU_IF},media=disk,format=raw" \
 		-device "virtio-net-pci,netdev=lan0,mac=52:54:00:65:43:21" \
 		-netdev "user,id=lan0,net=10.0.3.0/24,ipv6-net=fec7::/48,hostname=pizza,dnssearch=test,domainname=example.com,bootfile=/path/to/bootfile2" \
 		-device "virtio-net-pci,netdev=lan1,mac=52:54:00:12:34:56" \
 		-netdev "user,id=lan1,hostname=goulash,dnssearch=example,dnssearch=example.net,domainname=test,bootfile=/path/to/bootfile"
 	grep -qF "${INIT_MESSAGE}" "${OUTPUT}"
+}
+
+run_qemu_diskless_with_socket_network() {
+	local append="$1"
+	shift
+	_run_qemu "panic=-1 $append" \
+		-device "virtio-net-pci,netdev=lan0,mac=52:54:00:65:43:21" \
+		-netdev "socket,id=lan0,connect=localhost:1234" "$@"
+	grep -qF "${INIT_MESSAGE}" "${OUTPUT}"
+}
+
+run_qemu_with_socket_network() {
+	_run_qemu "root=/dev/${ROOTDISK_LINUX_NAME} panic=-1 $*" \
+		-drive "file=${ROOTDISK},if=${ROOTDISK_QEMU_IF},media=disk,format=raw" \
+		-device "virtio-net-pci,netdev=lan0,mac=52:54:00:65:43:21" \
+		-netdev "socket,id=lan0,connect=localhost:1234"
+	grep -qF "${INIT_MESSAGE}" "${OUTPUT}"
+}
+
+check_no_output() {
+	local msg="$1"
+	if grep -qF "${msg}" "${OUTPUT}"; then
+		echo >&2 "E: Message '${msg}' found in log output '${OUTPUT}."
+		exit 1
+	fi
 }
 
 check_output() {
@@ -194,4 +232,29 @@ check_output() {
 		echo >&2 "E: Message '${msg}' not found in log output '${OUTPUT}."
 		exit 1
 	fi
+}
+
+check_no_network_configuration() {
+	check_no_output "Waiting up to 180 secs for"
+}
+
+wait_for_server_startup() {
+	local expected_log_line="$1"
+	local qemu_logfile="$2"
+	local server_pid="$3"
+	local timeout="$QEMU_TIMEOUT"
+
+	while ! grep -q "$expected_log_line" "$qemu_logfile"; do
+		echo "Waiting up to $timeout seconds for server (QEMU process $server_pid) to get started..."
+		if ! test -d "/proc/$server_pid"; then
+			echo >&2 "Error: QEMU server process $server_pid disappeared."
+			return 1
+		fi
+		timeout=$((timeout - 1))
+		if test "$timeout" -le 0; then
+			echo >&2 "Error: server was not started within $QEMU_TIMEOUT seconds."
+			return 1
+		fi
+		sleep 1
+	done
 }
diff --git a/mkinitramfs b/mkinitramfs
--- a/mkinitramfs
+++ b/mkinitramfs
@@ -20,6 +20,7 @@ Usage: mkinitramfs [option]... -o outfile [version]
 Options:
   -c compress	Override COMPRESS setting in initramfs.conf.
   -d confdir	Specify an alternative configuration directory.
+  -l level	Override COMPRESSLEVEL setting in initramfs.conf.
   -k		Keep temporary directory used to make the image.
   -o outfile	Write to outfile.
   -r root	Override ROOT setting in initramfs.conf.
@@ -35,7 +36,7 @@ usage_error()
 	exit 2
 }
 
-OPTIONS=$(getopt -o c:d:hko:r:v --long help -n "$0" -- "$@") || usage_error
+OPTIONS=$(getopt -o c:d:hl:ko:r:v --long help -n "$0" -- "$@") || usage_error
 
 eval set -- "$OPTIONS"
 
@@ -56,6 +57,10 @@ while true; do
 	-h|--help)
 		usage
 		exit 0
+		;;
+	-l)
+		compresslevel="$2"
+		shift 2
 		;;
 	-o)
 		outfile="$2"
@@ -179,9 +184,49 @@ fi
 unset COMPRESS
 
 if ! command -v "${compress}" >/dev/null 2>&1; then
-	echo "No ${compress} in ${PATH}, using gzip"
+	echo "W: No ${compress} in ${PATH}, using gzip" >&2
 	compress=gzip
 fi
+
+# Check that kernel supports selected compressor, and fall back to gzip.
+# Exit if even gzip is not supported.
+case "${compress}" in
+gzip)	kconfig_sym=CONFIG_RD_GZIP ;;
+bzip2)	kconfig_sym=CONFIG_RD_BZIP2 ;;
+lzma)	kconfig_sym=CONFIG_RD_LZMA ;;
+xz)	kconfig_sym=CONFIG_RD_XZ ;;
+lzop)	kconfig_sym=CONFIG_RD_LZO ;;
+lz4)	kconfig_sym=CONFIG_RD_LZ4 ;;
+zstd)	kconfig_sym=CONFIG_RD_ZSTD ;;
+esac
+if [ -e "/boot/config-${version}" ]; then
+	while ! grep -q "^$kconfig_sym=y" "/boot/config-${version}"; do
+		if [ "${compress}" = gzip ]; then
+			echo "E: gzip compression ($kconfig_sym) not supported by kernel" >&2
+			exit 1
+		fi
+		echo "W: ${compress} compression ($kconfig_sym) not supported by kernel, using gzip" >&2
+		compress=gzip
+		kconfig_sym=CONFIG_RD_GZIP
+	done
+else
+	echo "W: Kernel configuration /boot/config-${version} is missing," \
+		"cannot check for ${compress} compression support ($kconfig_sym)" >&2
+fi
+
+if [ -z "${compresslevel:-}" ]; then
+	compresslevel=${COMPRESSLEVEL:-}
+fi
+case "${compress}" in
+lz4)	compresslevel="-${compresslevel:-2}" ;;
+zstd)	compresslevel="-${compresslevel:-1}" ;;
+#gzip|xz|bzip2|lzma|lzop included
+*)
+	# We're not using a compression level by default
+	compresslevel="${compresslevel:+-${compresslevel}}"
+	;;
+esac
+unset COMPRESSLEVEL
 
 case "${compress}" in
 gzip)	# If we're doing a reproducible build, use gzip -n
@@ -191,15 +236,21 @@ gzip)	# If we're doing a reproducible build, use gzip -n
 	elif command -v pigz >/dev/null; then
 		compress=pigz
 	fi
+	if [ -n "${compresslevel}" ]; then
+		compress="${compress} ${compresslevel}"
+	fi
 	;;
-lz4)	compress="lz4 -2 -l" ;;
-zstd)	compress="zstd -q -1 -T0" ;;
-xz)	compress="xz --check=crc32"
+lz4)	compress="lz4 ${compresslevel} -l" ;;
+zstd)	compress="zstd -q ${compresslevel}"
+	# If we're not doing a reproducible build, enable multithreading
+	test -z "${SOURCE_DATE_EPOCH}" && compress="$compress -T0"
+	;;
+xz)	compress="xz ${compresslevel} --check=crc32"
 	# If we're not doing a reproducible build, enable multithreading
 	test -z "${SOURCE_DATE_EPOCH}" && compress="$compress --threads=0"
 	;;
 bzip2|lzma|lzop)
-	# no parameters needed
+	compress="${compress} ${compresslevel}"
 	;;
 *)	echo "W: Unknown compression command ${compress}" >&2 ;;
 esac
@@ -221,17 +272,21 @@ fi
 
 # Prepare to clean up temporary files on exit
 DESTDIR=
+__TMPMAINFILES=
+__TMPUNCOMPRESSEDFILES=
 __TMPCPIOGZ=
-__TMPMAINCPIO=
 __TMPEARLYCPIO=
+__MODULES_TO_ADD=
+# shellcheck disable=SC2317
 clean_on_exit() {
 	if [ "${keep}" = "y" ]; then
 		echo "Working files in ${DESTDIR:-<not yet created>}," \
-			"early initramfs in ${__TMPEARLYCPIO:-<not yet created>}," \
-			"main initramfs in ${__TMPMAINCPIO:-<not yet created>} and" \
+			"list of files for main initramfs in ${__TMPMAINFILES:-<not yet created>}," \
+			"list of files for uncompressed initramfs in ${__TMPUNCOMPRESSEDFILES:-<not yet created>}," \
+			"early initramfs in ${__TMPEARLYCPIO:-<not yet created>} and" \
 			"overlay in ${__TMPCPIOGZ:-<not yet created>}"
 	else
-		for path in "${DESTDIR}" "${__TMPCPIOGZ}" "${__TMPMAINCPIO}" "${__TMPEARLYCPIO}"; do
+		for path in "${DESTDIR}" "${__TMPMAINFILES}" "${__TMPUNCOMPRESSEDFILES}" "${__TMPCPIOGZ}" "${__TMPEARLYCPIO}" "${__MODULES_TO_ADD}"; do
 			test -z "${path}" || rm -rf "${path}"
 		done
 	fi
@@ -243,9 +298,11 @@ trap "exit 1" INT TERM	# makes the EXIT trap effective even when killed
 [ -n "${TMPDIR}" ] && [ ! -w "${TMPDIR}" ] && unset TMPDIR
 DESTDIR="$(mktemp -d "${TMPDIR:-/var/tmp}/mkinitramfs_XXXXXX")" || exit 1
 chmod 755 "${DESTDIR}"
+__TMPMAINFILES="$(mktemp "${TMPDIR:-/var/tmp}/mkinitramfs-MAIN_files_XXXXXX")" || exit 1
+__TMPUNCOMPRESSEDFILES="$(mktemp "${TMPDIR:-/var/tmp}/mkinitramfs-UNCOMPRESSED_files_XXXXXX")" || exit 1
 __TMPCPIOGZ="$(mktemp "${TMPDIR:-/var/tmp}/mkinitramfs-OL_XXXXXX")" || exit 1
-__TMPMAINCPIO="$(mktemp "${TMPDIR:-/var/tmp}/mkinitramfs-MAIN_XXXXXX")" || exit 1
 __TMPEARLYCPIO="$(mktemp "${TMPDIR:-/var/tmp}/mkinitramfs-FW_XXXXXX")" || exit 1
+__MODULES_TO_ADD="$(mktemp "${TMPDIR:-/var/tmp}/modules_XXXXXX")" || exit 1
 
 DPKG_ARCH=$(dpkg --print-architecture)
 
@@ -268,6 +325,9 @@ export __TMPCPIOGZ
 # Private, used by 'prepend_earlyinitramfs'.
 export __TMPEARLYCPIO
 
+# Private, used by 'manual_add_modules'.
+export __MODULES_TO_ADD
+
 # Create usr-merged filesystem layout, to avoid duplicates if the host
 # filesystem is usr-merged.
 for d in /bin /lib* /sbin; do
@@ -278,10 +338,10 @@ for d in conf/conf.d etc run scripts ${MODULESDIR}; do
 	mkdir -p "${DESTDIR}/${d}"
 done
 
-# Copy in modules.builtin and modules.order (not generated by depmod)
+# Copy in modules.builtin, modules.builtin.modinfo and modules.order (not generated by depmod)
 # and modules.builtin.bin (generated by depmod, but too late to avoid
 # error messages as in #948257)
-for x in modules.builtin modules.builtin.bin modules.order; do
+for x in modules.builtin modules.builtin.bin modules.builtin.modinfo modules.order; do
 	if [ -f "${MODULESDIR}/${x}" ]; then
 		cp -p "${MODULESDIR}/${x}" "${DESTDIR}${MODULESDIR}/${x}"
 	fi
@@ -315,9 +375,6 @@ list)
 	auto_add_modules
 	;;
 esac
-
-# Resolve hidden dependencies
-hidden_dep_add_modules
 
 # Add firmware for built-in code
 add_builtin_firmware
@@ -384,7 +441,10 @@ for file in /etc/modprobe.d/*.conf /lib/modprobe.d/*.conf ; do
 	fi
 done
 
+export STAGE_KERNEL_MODULE_COPYING=1
 run_scripts_optional /usr/share/initramfs-tools/hooks
+unset STAGE_KERNEL_MODULE_COPYING
+apply_add_modules
 run_scripts_optional "${CONFDIR}"/hooks
 
 # cache boot run order
@@ -392,23 +452,8 @@ for b in $(cd "${DESTDIR}/scripts" && find . -mindepth 1 -type d); do
 	cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
 done
 
-# decompress modules for boot speed, if possible
-find "${DESTDIR}/${MODULESDIR}" -name '*.ko.*' | while read -r ko; do
-	case "$ko" in
-	*.xz)
-		if ! command -v xz >/dev/null 2>&1; then
-			break
-		fi
-		xz -d "${ko}"
-		;;
-	*.zst)
-		if ! command -v zstd >/dev/null 2>&1; then
-			break
-		fi
-		zstd -q -d --rm "${ko}"
-		;;
-	esac
-done
+# Resolve hidden dependencies
+hidden_dep_add_modules
 
 # generate module deps
 depmod -a -b "${DESTDIR}" "${version}"
@@ -438,12 +483,12 @@ esac
 
 # Remove any looping or broken symbolic links, since they break cpio.
 [ "${verbose}" = y ] && xargs_verbose="-t"
+# shellcheck disable=SC2086
 (cd "${DESTDIR}" && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' \
 	| xargs ${xargs_verbose:-} -rL1 rm -f)
 
 [ "${verbose}" = y ] && echo "Building cpio ${outfile} initramfs"
 
-(
 # preserve permissions if root builds the image, see #633582
 [ "$(id -ru)" != 0 ] && cpio_owner_root="-R 0:0"
 
@@ -457,46 +502,70 @@ if [ -n "${SOURCE_DATE_EPOCH}" ]; then
 	cpio_reproducible="--reproducible"
 fi
 
-# work around lack of "set -o pipefail" for the following pipe:
-# cd "${DESTDIR}" && find . | LC_ALL=C sort | cpio --quiet $cpio_owner_root $cpio_reproducible -o -H newc >>"${outfile}" || exit 1
-ec1=1
-ec2=1
-exec 3>&1
-eval "$(
-	# http://cfaj.freeshell.org/shell/cus-faq-2.html
-	exec 4>&1 >&3 3>&-
-	cd  "${DESTDIR}"
+# Read list of files and echo them plus all leading directories.
+# The same directories might be printed multiple times (even with sorted input)!
+add_directories() {
+	local last_dir path dir
+	while read -r path; do
+		dir="${path%/*}"
+		parent="${dir}"
+		while [ "$parent" != "$last_dir" ] && [ "$parent" != "." ]; do
+			echo "$parent"
+			parent="${parent%/*}"
+		done
+		last_dir="$dir"
+		echo "$path"
+	done
+	if [ -n "$last_dir" ]; then
+		echo "."
+	fi
+}
+
+cd  "${DESTDIR}" || exit 1
+
+# work around lack of "set -o pipefail" for pipes.
+# Write exit code to FD 3 in case of a failure to pass it through the pipes.
+{
 	{
-		find . 4>&-; echo "ec1=$?;" >&4
-	} | {
-		LC_ALL=C sort
-	} | {
-		# shellcheck disable=SC2086
-		cpio --quiet $cpio_owner_root $cpio_reproducible -o -H newc 4>&- >"${__TMPMAINCPIO}"
-		echo "ec2=$?;" >&4
-	}
-)"
-if [ "$ec1" -ne 0 ]; then
-	echo "E: mkinitramfs failure find $ec1 cpio $ec2" >&2
-	exit "$ec1"
-fi
-if [ "$ec2" -ne 0 ]; then
-	echo "E: mkinitramfs failure cpio $ec2" >&2
-	exit "$ec2"
-fi
-) || exit 1
+		find . \( ! -type d ! -name '*.zst' ! -name '*.xz' \) -o \( -type d -empty \) ||
+			{ echo "E: mkinitramfs failure main find $?" >&2; echo 1 >&3; exit; }
+	} | add_directories | {
+		LC_ALL=C sort || { echo "E: mkinitramfs failure sort $?" >&2; echo 1 >&3; exit; }
+	} | uniq > "${__TMPMAINFILES}" || { echo "E: mkinitramfs failure uniq $?" >&2; echo 1 >&3; exit; }
+} 3>&1 | { read -r exit_code; exit "${exit_code:-0}"; } || exit $?
 
 {
-if [ -s "${__TMPEARLYCPIO}" ]; then
-	cat "${__TMPEARLYCPIO}" || exit 1
-fi
+	{
+		find . -name '*.zst' -o -name '*.xz' ||
+			{ echo "E: mkinitramfs failure uncompressed find $?" >&2; echo 1 >&3; exit; }
+	} | add_directories | {
+		LC_ALL=C sort || { echo "E: mkinitramfs failure sort $?" >&2; echo 1 >&3; exit; }
+	} | uniq > "${__TMPUNCOMPRESSEDFILES}" || { echo "E: mkinitramfs failure uniq $?" >&2; echo 1 >&3; exit; }
+} 3>&1 | { read -r exit_code; exit "${exit_code:-0}"; } || exit $?
 
-$compress -c "${__TMPMAINCPIO}" ||
-	{ echo "E: mkinitramfs failure $compress $?" >&2; exit 1; }
+{
+	{
+		if [ -s "${__TMPEARLYCPIO}" ]; then
+			cat "${__TMPEARLYCPIO}" || { echo 1 >&3; exit; }
+		fi
 
-if [ -s "${__TMPCPIOGZ}" ]; then
-	cat "${__TMPCPIOGZ}" || exit 1
-fi
-} >"${outfile}" || exit 1
+		if [ -s "${__TMPUNCOMPRESSEDFILES}" ]; then
+			# shellcheck disable=SC2086
+			cpio --quiet $cpio_owner_root $cpio_reproducible -o -H newc -D "${DESTDIR}" <"${__TMPUNCOMPRESSEDFILES}" ||
+				{ echo "E: mkinitramfs failure uncompressed cpio $?" >&2; echo 1 >&3; exit; }
+		fi
+
+		{
+			# shellcheck disable=SC2086
+			cpio --quiet $cpio_owner_root $cpio_reproducible -o -H newc -D "${DESTDIR}" <"${__TMPMAINFILES}" ||
+				{ echo "E: mkinitramfs failure cpio $?" >&2; echo 1 >&3; exit; }
+		} | $compress -c ||
+			{ echo "E: mkinitramfs failure $compress $?" >&2; echo 1 >&3; exit; }
+
+		if [ -s "${__TMPCPIOGZ}" ]; then
+			cat "${__TMPCPIOGZ}" || { echo 1 >&3; exit; }
+		fi
+	} >"${outfile}" || echo $? >&3
+} 3>&1 | { read -r exit_code; exit "${exit_code:-0}"; } || exit $?
 
 exit 0
